# Parameter set for outdoor environment (e.g. KITTI Odometry Dataset or short experiment sequence of Newer College Dataset)

# topic: (set in launch file or command line)
deskew: true
max_range: 70.0
min_range: 0.5
voxel_size: 0.05
desired_num_voxelized_points: 2000
planarity_threshold: 0.1
max_points_per_voxel: 100
initial_threshold: 2.0
min_motion_th: 0.1
max_num_iterations: 150
convergence_criterion: 0.0001
